#!/bin/sh
#
#   /etc/NetworkManager/dispatcher.d/wlan-up.d/default
#       Default action for WiFi interface coming up.
#
#   Copyright (C) 2017  Steven Bakker
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

IFACE="$1"
ACTION="$2"
CONN_NAME="$3"
shift 3

myname=$(basename "$0") || exit 1

log() { logger -p user.info -t "${myname}[$$]" "$IFACE/$ACTION/$CONN_NAME: $*"; }

log "nothing to do"

# log "disable IPv6 on a broken network"
# disable_ipv6.sh "$@"
